[platformio]
default_envs = coordinator

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:coordinator]
lib_deps =
	workloads/SCServo @ ^1.0.1
	ESP32Async/AsyncTCP @ ^3.3.2
	ESP32Async/ESPAsyncWebServer @ ^3.6.0
build_src_filter =
	+<main.cpp>

[env:servo_id_setter]
lib_deps =
	workloads/SCServo @ ^1.0.1
build_src_filter =
	+<servo_id_setter.cpp>

[env:servo_id_reader]
lib_deps =
	workloads/SCServo @ ^1.0.1
build_src_filter =
	+<servo_id_reader.cpp>

[env:servo_center_setter]
build_src_filter =
	+<servo_center_setter.cpp>

[env:node]
lib_deps =
	workloads/SCServo @ ^1.0.1
build_src_filter =
	+<main_node.cpp>
build_flags =
	${env.build_flags}
	-DNODE_ID=1

[env:node2]
lib_deps =
	workloads/SCServo @ ^1.0.1
build_src_filter =
	+<main_node.cpp>
build_flags =
	${env.build_flags}
	-DNODE_ID=2

[env:node3]
lib_deps =
	workloads/SCServo @ ^1.0.1
build_src_filter =
	+<main_node.cpp>
build_flags =
	${env.build_flags}
	-DNODE_ID=3
